stages:
  - update
image: node:16.16.0
update_master_job:
  stage: update
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  only:
    - master
  script:
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - yarn install --frozen-lockfile
    - CI=false yarn run build
    - scp -r dist/* ${SERVER_USER}@${SERVER_URL}:${SERVER_PATH}
